name: Build and Test
on:
  push:
    branches: [ galactic ]
  pull_request:
    branches: [ galactic ]
  schedule:
    - cron: '0 21 * * *'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-desktop-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic
      - name: Setup Ignition Gazebo
        run: sudo .github/workflows/setup_ignition.sh
      - name: Build rmoss_ign
        uses: ros-tooling/action-ros-ci@v0.2
        env:
          IGNITION_VERSION: edifice
        with:
          target-ros2-distro: galactic
          vcs-repo-file-url: "${{ github.workspace }}/tools/dependency.repos"
          skip-tests: true
      - name: Test rmoss_ign_base
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh rmoss_ign_base
        env:
          IGNITION_VERSION: edifice
      - name: Test rmoss_ign_cam
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh rmoss_ign_cam
        env:
          IGNITION_VERSION: edifice
